// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countActiveSessionsByStaff = `-- name: CountActiveSessionsByStaff :one
SELECT COUNT(*) AS count FROM refresh_tokens
WHERE staff_id = ? AND expires_at > NOW()
`

func (q *Queries) CountActiveSessionsByStaff(ctx context.Context, staffID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSessionsByStaff, staffID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, staff_id, token_hash, user_agent, ip_address, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, NOW())
`

type CreateRefreshTokenParams struct {
	ID        string         `json:"id"`
	StaffID   string         `json:"staff_id"`
	TokenHash string         `json:"token_hash"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.StaffID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const deleteOldestSessionByStaff = `-- name: DeleteOldestSessionByStaff :exec
DELETE FROM refresh_tokens
WHERE id = (
    SELECT id FROM (
        SELECT rt.id FROM refresh_tokens AS rt
        WHERE rt.staff_id = ? AND rt.expires_at > NOW()
        ORDER BY rt.last_used_at ASC
        LIMIT 1
    ) AS oldest
)
`

func (q *Queries) DeleteOldestSessionByStaff(ctx context.Context, staffID string) error {
	_, err := q.db.ExecContext(ctx, deleteOldestSessionByStaff, staffID)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE token_hash = ?
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, tokenHash)
	return err
}

const deleteRefreshTokensByStaff = `-- name: DeleteRefreshTokensByStaff :exec
DELETE FROM refresh_tokens WHERE staff_id = ?
`

func (q *Queries) DeleteRefreshTokensByStaff(ctx context.Context, staffID string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByStaff, staffID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, staff_id, token_hash, user_agent, ip_address, expires_at, last_used_at, created_at FROM refresh_tokens
WHERE token_hash = ? AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, username, password_hash, email, role, full_name, phone, is_active, created_at, updated_at, deleted_at FROM staff
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetStaffByID(ctx context.Context, id string) (Staff, error) {
	row := q.db.QueryRowContext(ctx, getStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStaffByUsername = `-- name: GetStaffByUsername :one
SELECT id, username, password_hash, email, role, full_name, phone, is_active, created_at, updated_at, deleted_at FROM staff
WHERE username = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetStaffByUsername(ctx context.Context, username string) (Staff, error) {
	row := q.db.QueryRowContext(ctx, getStaffByUsername, username)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveSessionsByStaff = `-- name: ListActiveSessionsByStaff :many
SELECT id, staff_id, token_hash, user_agent, ip_address, expires_at, last_used_at, created_at FROM refresh_tokens
WHERE staff_id = ? AND expires_at > NOW()
ORDER BY last_used_at ASC
`

func (q *Queries) ListActiveSessionsByStaff(ctx context.Context, staffID string) ([]RefreshToken, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSessionsByStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.TokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStaffActive = `-- name: SetStaffActive :exec
UPDATE staff SET is_active = ?, updated_at = NOW() WHERE id = ?
`

func (q *Queries) SetStaffActive(ctx context.Context, isActive bool, iD string) error {
	_, err := q.db.ExecContext(ctx, setStaffActive, isActive, iD)
	return err
}

const updateRefreshTokenLastUsed = `-- name: UpdateRefreshTokenLastUsed :exec
UPDATE refresh_tokens SET last_used_at = NOW() WHERE token_hash = ?
`

func (q *Queries) UpdateRefreshTokenLastUsed(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenLastUsed, tokenHash)
	return err
}
