// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"
	"database/sql"
)

const createFileAttachment = `-- name: CreateFileAttachment :exec
INSERT INTO file_attachments (id, object_path, original_name, mime_type, size_bytes, uploaded_by, is_orphan)
VALUES (?, ?, ?, ?, ?, ?, 1)
`

type CreateFileAttachmentParams struct {
	ID           string         `json:"id"`
	ObjectPath   string         `json:"object_path"`
	OriginalName string         `json:"original_name"`
	MimeType     string         `json:"mime_type"`
	SizeBytes    int64          `json:"size_bytes"`
	UploadedBy   sql.NullString `json:"uploaded_by"`
}

func (q *Queries) CreateFileAttachment(ctx context.Context, arg CreateFileAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createFileAttachment,
		arg.ID,
		arg.ObjectPath,
		arg.OriginalName,
		arg.MimeType,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	return err
}

const deleteOrphanFilesOlderThan24h = `-- name: DeleteOrphanFilesOlderThan24h :exec
DELETE FROM file_attachments
WHERE is_orphan = 1
  AND created_at < DATE_SUB(NOW(), INTERVAL 24 HOUR)
`

func (q *Queries) DeleteOrphanFilesOlderThan24h(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanFilesOlderThan24h)
	return err
}

const getFileAttachmentByID = `-- name: GetFileAttachmentByID :one
SELECT id, object_path, original_name, mime_type, size_bytes, uploaded_by, is_orphan, entity_type, entity_id, created_at, updated_at FROM file_attachments
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetFileAttachmentByID(ctx context.Context, id string) (FileAttachment, error) {
	row := q.db.QueryRowContext(ctx, getFileAttachmentByID, id)
	var i FileAttachment
	err := row.Scan(
		&i.ID,
		&i.ObjectPath,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.IsOrphan,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkFileToEntity = `-- name: LinkFileToEntity :exec
UPDATE file_attachments
SET is_orphan = 0, entity_type = ?, entity_id = ?, updated_at = NOW()
WHERE id = ?
`

func (q *Queries) LinkFileToEntity(ctx context.Context, entityType sql.NullString, entityID sql.NullString, iD string) error {
	_, err := q.db.ExecContext(ctx, linkFileToEntity, entityType, entityID, iD)
	return err
}

const listOrphanFilesOlderThan24h = `-- name: ListOrphanFilesOlderThan24h :many
SELECT id, object_path, original_name, mime_type, size_bytes, uploaded_by, is_orphan, entity_type, entity_id, created_at, updated_at FROM file_attachments
WHERE is_orphan = 1
  AND created_at < DATE_SUB(NOW(), INTERVAL 24 HOUR)
`

func (q *Queries) ListOrphanFilesOlderThan24h(ctx context.Context) ([]FileAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanFilesOlderThan24h)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileAttachment{}
	for rows.Next() {
		var i FileAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ObjectPath,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.IsOrphan,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
