// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type OrdersSource string

const (
	OrdersSourceOnline OrdersSource = "online"
	OrdersSourceQr     OrdersSource = "qr"
	OrdersSourcePos    OrdersSource = "pos"
)

func (e *OrdersSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersSource(s)
	case string:
		*e = OrdersSource(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersSource: %T", src)
	}
	return nil
}

type NullOrdersSource struct {
	OrdersSource OrdersSource `json:"orders_source"`
	Valid        bool         `json:"valid"` // Valid is true if OrdersSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersSource) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersSource), nil
}

type OrdersStatus string

const (
	OrdersStatusPending   OrdersStatus = "pending"
	OrdersStatusConfirmed OrdersStatus = "confirmed"
	OrdersStatusPreparing OrdersStatus = "preparing"
	OrdersStatusReady     OrdersStatus = "ready"
	OrdersStatusDelivered OrdersStatus = "delivered"
	OrdersStatusCancelled OrdersStatus = "cancelled"
)

func (e *OrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersStatus(s)
	case string:
		*e = OrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersStatus: %T", src)
	}
	return nil
}

type NullOrdersStatus struct {
	OrdersStatus OrdersStatus `json:"orders_status"`
	Valid        bool         `json:"valid"` // Valid is true if OrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersStatus), nil
}

type PaymentsMethod string

const (
	PaymentsMethodVnpay   PaymentsMethod = "vnpay"
	PaymentsMethodMomo    PaymentsMethod = "momo"
	PaymentsMethodZalopay PaymentsMethod = "zalopay"
	PaymentsMethodCash    PaymentsMethod = "cash"
)

func (e *PaymentsMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentsMethod(s)
	case string:
		*e = PaymentsMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentsMethod: %T", src)
	}
	return nil
}

type NullPaymentsMethod struct {
	PaymentsMethod PaymentsMethod `json:"payments_method"`
	Valid          bool           `json:"valid"` // Valid is true if PaymentsMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentsMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentsMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentsMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentsMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentsMethod), nil
}

type PaymentsStatus string

const (
	PaymentsStatusPending   PaymentsStatus = "pending"
	PaymentsStatusCompleted PaymentsStatus = "completed"
	PaymentsStatusFailed    PaymentsStatus = "failed"
	PaymentsStatusRefunded  PaymentsStatus = "refunded"
)

func (e *PaymentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentsStatus(s)
	case string:
		*e = PaymentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentsStatus: %T", src)
	}
	return nil
}

type NullPaymentsStatus struct {
	PaymentsStatus PaymentsStatus `json:"payments_status"`
	Valid          bool           `json:"valid"` // Valid is true if PaymentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentsStatus), nil
}

type StaffRole string

const (
	StaffRoleCustomer StaffRole = "customer"
	StaffRoleChef     StaffRole = "chef"
	StaffRoleCashier  StaffRole = "cashier"
	StaffRoleStaff    StaffRole = "staff"
	StaffRoleManager  StaffRole = "manager"
	StaffRoleAdmin    StaffRole = "admin"
)

func (e *StaffRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StaffRole(s)
	case string:
		*e = StaffRole(s)
	default:
		return fmt.Errorf("unsupported scan type for StaffRole: %T", src)
	}
	return nil
}

type NullStaffRole struct {
	StaffRole StaffRole `json:"staff_role"`
	Valid     bool      `json:"valid"` // Valid is true if StaffRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStaffRole) Scan(value interface{}) error {
	if value == nil {
		ns.StaffRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StaffRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStaffRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StaffRole), nil
}

type StaffTasksPriority string

const (
	StaffTasksPriorityHigh   StaffTasksPriority = "high"
	StaffTasksPriorityMedium StaffTasksPriority = "medium"
	StaffTasksPriorityLow    StaffTasksPriority = "low"
)

func (e *StaffTasksPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StaffTasksPriority(s)
	case string:
		*e = StaffTasksPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for StaffTasksPriority: %T", src)
	}
	return nil
}

type NullStaffTasksPriority struct {
	StaffTasksPriority StaffTasksPriority `json:"staff_tasks_priority"`
	Valid              bool               `json:"valid"` // Valid is true if StaffTasksPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStaffTasksPriority) Scan(value interface{}) error {
	if value == nil {
		ns.StaffTasksPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StaffTasksPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStaffTasksPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StaffTasksPriority), nil
}

type StaffTasksStatus string

const (
	StaffTasksStatusPending    StaffTasksStatus = "pending"
	StaffTasksStatusInProgress StaffTasksStatus = "in_progress"
	StaffTasksStatusCompleted  StaffTasksStatus = "completed"
	StaffTasksStatusOverdue    StaffTasksStatus = "overdue"
)

func (e *StaffTasksStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StaffTasksStatus(s)
	case string:
		*e = StaffTasksStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StaffTasksStatus: %T", src)
	}
	return nil
}

type NullStaffTasksStatus struct {
	StaffTasksStatus StaffTasksStatus `json:"staff_tasks_status"`
	Valid            bool             `json:"valid"` // Valid is true if StaffTasksStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStaffTasksStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StaffTasksStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StaffTasksStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStaffTasksStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StaffTasksStatus), nil
}

type StockMovementsType string

const (
	StockMovementsTypeIn         StockMovementsType = "in"
	StockMovementsTypeOut        StockMovementsType = "out"
	StockMovementsTypeAdjustment StockMovementsType = "adjustment"
)

func (e *StockMovementsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockMovementsType(s)
	case string:
		*e = StockMovementsType(s)
	default:
		return fmt.Errorf("unsupported scan type for StockMovementsType: %T", src)
	}
	return nil
}

type NullStockMovementsType struct {
	StockMovementsType StockMovementsType `json:"stock_movements_type"`
	Valid              bool               `json:"valid"` // Valid is true if StockMovementsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockMovementsType) Scan(value interface{}) error {
	if value == nil {
		ns.StockMovementsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockMovementsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockMovementsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockMovementsType), nil
}

type TablesStatus string

const (
	TablesStatusAvailable TablesStatus = "available"
	TablesStatusOccupied  TablesStatus = "occupied"
	TablesStatusReserved  TablesStatus = "reserved"
	TablesStatusInactive  TablesStatus = "inactive"
)

func (e *TablesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TablesStatus(s)
	case string:
		*e = TablesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TablesStatus: %T", src)
	}
	return nil
}

type NullTablesStatus struct {
	TablesStatus TablesStatus `json:"tables_status"`
	Valid        bool         `json:"valid"` // Valid is true if TablesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTablesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TablesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TablesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTablesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TablesStatus), nil
}

type TrainingGuideRolesRole string

const (
	TrainingGuideRolesRoleChef    TrainingGuideRolesRole = "chef"
	TrainingGuideRolesRoleCashier TrainingGuideRolesRole = "cashier"
	TrainingGuideRolesRoleStaff   TrainingGuideRolesRole = "staff"
	TrainingGuideRolesRoleManager TrainingGuideRolesRole = "manager"
)

func (e *TrainingGuideRolesRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrainingGuideRolesRole(s)
	case string:
		*e = TrainingGuideRolesRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TrainingGuideRolesRole: %T", src)
	}
	return nil
}

type NullTrainingGuideRolesRole struct {
	TrainingGuideRolesRole TrainingGuideRolesRole `json:"training_guide_roles_role"`
	Valid                  bool                   `json:"valid"` // Valid is true if TrainingGuideRolesRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrainingGuideRolesRole) Scan(value interface{}) error {
	if value == nil {
		ns.TrainingGuideRolesRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrainingGuideRolesRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrainingGuideRolesRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrainingGuideRolesRole), nil
}

type TrainingGuidesRole string

const (
	TrainingGuidesRoleChef    TrainingGuidesRole = "chef"
	TrainingGuidesRoleCashier TrainingGuidesRole = "cashier"
	TrainingGuidesRoleStaff   TrainingGuidesRole = "staff"
	TrainingGuidesRoleManager TrainingGuidesRole = "manager"
)

func (e *TrainingGuidesRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrainingGuidesRole(s)
	case string:
		*e = TrainingGuidesRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TrainingGuidesRole: %T", src)
	}
	return nil
}

type NullTrainingGuidesRole struct {
	TrainingGuidesRole TrainingGuidesRole `json:"training_guides_role"`
	Valid              bool               `json:"valid"` // Valid is true if TrainingGuidesRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrainingGuidesRole) Scan(value interface{}) error {
	if value == nil {
		ns.TrainingGuidesRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrainingGuidesRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrainingGuidesRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrainingGuidesRole), nil
}

type Category struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SortOrder   int32          `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Combo struct {
	ID          string         `json:"id"`
	CategoryID  sql.NullString `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	ImagePath   sql.NullString `json:"image_path"`
	IsAvailable bool           `json:"is_available"`
	SortOrder   int32          `json:"sort_order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type ComboItem struct {
	ID        string    `json:"id"`
	ComboID   string    `json:"combo_id"`
	ProductID string    `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type FileAttachment struct {
	ID           string         `json:"id"`
	ObjectPath   string         `json:"object_path"`
	OriginalName string         `json:"original_name"`
	MimeType     string         `json:"mime_type"`
	SizeBytes    int64          `json:"size_bytes"`
	UploadedBy   sql.NullString `json:"uploaded_by"`
	IsOrphan     bool           `json:"is_orphan"`
	EntityType   sql.NullString `json:"entity_type"`
	EntityID     sql.NullString `json:"entity_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Ingredient struct {
	ID           string       `json:"id"`
	Name         string       `json:"name"`
	Unit         string       `json:"unit"`
	CurrentStock string       `json:"current_stock"`
	MinStock     string       `json:"min_stock"`
	CostPerUnit  string       `json:"cost_per_unit"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	ImportDate   time.Time    `json:"import_date"`
	ShelfDays    int32        `json:"shelf_days"`
}

type Order struct {
	ID            string         `json:"id"`
	OrderNumber   string         `json:"order_number"`
	TableID       sql.NullString `json:"table_id"`
	Status        OrdersStatus   `json:"status"`
	Source        OrdersSource   `json:"source"`
	CustomerName  sql.NullString `json:"customer_name"`
	CustomerPhone sql.NullString `json:"customer_phone"`
	Note          sql.NullString `json:"note"`
	TotalAmount   string         `json:"total_amount"`
	CreatedBy     sql.NullString `json:"created_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	// Shared UUID for multi-table group (Option A). NULL = standalone order.
	GroupID sql.NullString `json:"group_id"`
}

type OrderItem struct {
	ID               string          `json:"id"`
	OrderID          string          `json:"order_id"`
	ProductID        sql.NullString  `json:"product_id"`
	ComboID          sql.NullString  `json:"combo_id"`
	ComboRefID       sql.NullString  `json:"combo_ref_id"`
	Name             string          `json:"name"`
	UnitPrice        string          `json:"unit_price"`
	Quantity         int32           `json:"quantity"`
	QtyServed        int32           `json:"qty_served"`
	ToppingsSnapshot json.RawMessage `json:"toppings_snapshot"`
	Note             sql.NullString  `json:"note"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type OrderSequence struct {
	ID      int32     `json:"id"`
	DateKey time.Time `json:"date_key"`
	LastSeq int32     `json:"last_seq"`
}

type Payment struct {
	ID             string          `json:"id"`
	OrderID        string          `json:"order_id"`
	Method         PaymentsMethod  `json:"method"`
	Status         PaymentsStatus  `json:"status"`
	Amount         string          `json:"amount"`
	AttemptCount   int32           `json:"attempt_count"`
	GatewayRef     sql.NullString  `json:"gateway_ref"`
	GatewayData    json.RawMessage `json:"gateway_data"`
	RefundedAmount sql.NullString  `json:"refunded_amount"`
	ExpiresAt      sql.NullTime    `json:"expires_at"`
	PaidAt         sql.NullTime    `json:"paid_at"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	DeletedAt      sql.NullTime    `json:"deleted_at"`
}

type Product struct {
	ID          string         `json:"id"`
	CategoryID  string         `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	ImagePath   sql.NullString `json:"image_path"`
	IsAvailable bool           `json:"is_available"`
	SortOrder   int32          `json:"sort_order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type ProductIngredient struct {
	ProductID    string `json:"product_id"`
	IngredientID string `json:"ingredient_id"`
	QtyUsed      string `json:"qty_used"`
}

type ProductTopping struct {
	ProductID string `json:"product_id"`
	ToppingID string `json:"topping_id"`
}

type QuizAttempt struct {
	ID          string    `json:"id"`
	ProgressID  string    `json:"progress_id"`
	Score       int32     `json:"score"`
	Passed      bool      `json:"passed"`
	AttemptedAt time.Time `json:"attempted_at"`
	CreatedAt   time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID         string         `json:"id"`
	StaffID    string         `json:"staff_id"`
	TokenHash  string         `json:"token_hash"`
	UserAgent  sql.NullString `json:"user_agent"`
	IpAddress  sql.NullString `json:"ip_address"`
	ExpiresAt  time.Time      `json:"expires_at"`
	LastUsedAt sql.NullTime   `json:"last_used_at"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Staff struct {
	ID               string          `json:"id"`
	Username         string          `json:"username"`
	PasswordHash     string          `json:"password_hash"`
	Email            sql.NullString  `json:"email"`
	Role             StaffRole       `json:"role"`
	FullName         string          `json:"full_name"`
	Phone            sql.NullString  `json:"phone"`
	IsActive         bool            `json:"is_active"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	DeletedAt        sql.NullTime    `json:"deleted_at"`
	JobTitle         sql.NullString  `json:"job_title"`
	Shifts           json.RawMessage `json:"shifts"`
	Responsibilities sql.NullString  `json:"responsibilities"`
}

type StaffTask struct {
	ID           string             `json:"id"`
	Title        string             `json:"title"`
	Description  sql.NullString     `json:"description"`
	AssignedTo   string             `json:"assigned_to"`
	AssignedBy   string             `json:"assigned_by"`
	DueAt        time.Time          `json:"due_at"`
	CompletedAt  sql.NullTime       `json:"completed_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    sql.NullTime       `json:"deleted_at"`
	Priority     StaffTasksPriority `json:"priority"`
	Notes        sql.NullString     `json:"notes"`
	DueTimeStart sql.NullString     `json:"due_time_start"`
	DueTimeEnd   sql.NullString     `json:"due_time_end"`
	Status       StaffTasksStatus   `json:"status"`
}

type StockMovement struct {
	ID           string             `json:"id"`
	IngredientID string             `json:"ingredient_id"`
	Type         StockMovementsType `json:"type"`
	Quantity     string             `json:"quantity"`
	Note         sql.NullString     `json:"note"`
	CreatedBy    sql.NullString     `json:"created_by"`
	CreatedAt    time.Time          `json:"created_at"`
}

type Table struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	QrToken   string       `json:"qr_token"`
	Capacity  int32        `json:"capacity"`
	Status    TablesStatus `json:"status"`
	IsActive  bool         `json:"is_active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Topping struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Price       string       `json:"price"`
	IsAvailable bool         `json:"is_available"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

type TrainingGuide struct {
	ID                string             `json:"id"`
	Title             string             `json:"title"`
	Role              TrainingGuidesRole `json:"role"`
	Description       sql.NullString     `json:"description"`
	CoverImageUrl     sql.NullString     `json:"cover_image_url"`
	YoutubeUrl        sql.NullString     `json:"youtube_url"`
	QualityKpiTarget  sql.NullString     `json:"quality_kpi_target"`
	QuantityKpiTarget sql.NullString     `json:"quantity_kpi_target"`
	PassThreshold     int32              `json:"pass_threshold"`
	MaxAttempts       int32              `json:"max_attempts"`
	Published         bool               `json:"published"`
	CreatedBy         sql.NullString     `json:"created_by"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         sql.NullTime       `json:"deleted_at"`
}

type TrainingGuideRole struct {
	GuideID string                 `json:"guide_id"`
	Role    TrainingGuideRolesRole `json:"role"`
}

type TrainingProgress struct {
	ID             string         `json:"id"`
	GuideID        string         `json:"guide_id"`
	StaffID        string         `json:"staff_id"`
	WatchedPercent int32          `json:"watched_percent"`
	ManagerNotes   sql.NullString `json:"manager_notes"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
