// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, order_number, table_id, status, source, customer_name, customer_phone, note, total_amount, created_by)
VALUES (?, ?, ?, 'pending', ?, ?, ?, ?, 0, ?)
`

type CreateOrderParams struct {
	ID            string         `json:"id"`
	OrderNumber   string         `json:"order_number"`
	TableID       sql.NullString `json:"table_id"`
	Source        OrdersSource   `json:"source"`
	CustomerName  sql.NullString `json:"customer_name"`
	CustomerPhone sql.NullString `json:"customer_phone"`
	Note          sql.NullString `json:"note"`
	CreatedBy     sql.NullString `json:"created_by"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.OrderNumber,
		arg.TableID,
		arg.Source,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.Note,
		arg.CreatedBy,
	)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (id, order_id, product_id, combo_id, combo_ref_id, name, unit_price, quantity, qty_served, toppings_snapshot, note)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?)
`

type CreateOrderItemParams struct {
	ID               string          `json:"id"`
	OrderID          string          `json:"order_id"`
	ProductID        sql.NullString  `json:"product_id"`
	ComboID          sql.NullString  `json:"combo_id"`
	ComboRefID       sql.NullString  `json:"combo_ref_id"`
	Name             string          `json:"name"`
	UnitPrice        string          `json:"unit_price"`
	Quantity         int32           `json:"quantity"`
	ToppingsSnapshot json.RawMessage `json:"toppings_snapshot"`
	Note             sql.NullString  `json:"note"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.ComboID,
		arg.ComboRefID,
		arg.Name,
		arg.UnitPrice,
		arg.Quantity,
		arg.ToppingsSnapshot,
		arg.Note,
	)
	return err
}

const getActiveOrderByTable = `-- name: GetActiveOrderByTable :one
SELECT id, order_number, table_id, status, source, customer_name, customer_phone, note, total_amount, created_by, created_at, updated_at, deleted_at FROM orders
WHERE table_id = ?
  AND status IN ('pending','confirmed','preparing','ready')
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveOrderByTable(ctx context.Context, tableID sql.NullString) (Order, error) {
	row := q.db.QueryRowContext(ctx, getActiveOrderByTable, tableID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.TableID,
		&i.Status,
		&i.Source,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Note,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_number, table_id, status, source, customer_name, customer_phone, note, total_amount, created_by, created_at, updated_at, deleted_at FROM orders
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.TableID,
		&i.Status,
		&i.Source,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Note,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT id, order_id, product_id, combo_id, combo_ref_id, name, unit_price, quantity, qty_served, toppings_snapshot, note, created_at, updated_at FROM order_items
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetOrderItemByID(ctx context.Context, id string) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, getOrderItemByID, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ComboID,
		&i.ComboRefID,
		&i.Name,
		&i.UnitPrice,
		&i.Quantity,
		&i.QtyServed,
		&i.ToppingsSnapshot,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, product_id, combo_id, combo_ref_id, name, unit_price, quantity, qty_served, toppings_snapshot, note, created_at, updated_at FROM order_items
WHERE order_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ComboID,
			&i.ComboRefID,
			&i.Name,
			&i.UnitPrice,
			&i.Quantity,
			&i.QtyServed,
			&i.ToppingsSnapshot,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderSequence = `-- name: GetOrderSequence :one
SELECT last_seq FROM order_sequences
WHERE date_key = ?
LIMIT 1
`

func (q *Queries) GetOrderSequence(ctx context.Context, dateKey time.Time) (int32, error) {
	row := q.db.QueryRowContext(ctx, getOrderSequence, dateKey)
	var last_seq int32
	err := row.Scan(&last_seq)
	return last_seq, err
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT id, order_number, table_id, status, source, customer_name, customer_phone, note, total_amount, created_by, created_at, updated_at, deleted_at FROM orders
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

func (q *Queries) ListAllOrders(ctx context.Context, limit int32, offset int32) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listAllOrders, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.TableID,
			&i.Status,
			&i.Source,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Note,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT id, order_number, table_id, status, source, customer_name, customer_phone, note, total_amount, created_by, created_at, updated_at, deleted_at FROM orders
WHERE status = ? AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

func (q *Queries) ListOrdersByStatus(ctx context.Context, status OrdersStatus, limit int32, offset int32) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByStatus, status, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.TableID,
			&i.Status,
			&i.Source,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Note,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateTotalAmount = `-- name: RecalculateTotalAmount :exec
UPDATE orders
SET total_amount = (
    SELECT COALESCE(SUM(unit_price * quantity), 0)
    FROM order_items
    WHERE order_id = orders.id
),
updated_at = NOW()
WHERE orders.id = ?
`

// recalculateTotalAmount MUST be called after every order_items mutation.
// Skipping this causes total_amount drift and wrong payment charges.
func (q *Queries) RecalculateTotalAmount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, recalculateTotalAmount, id)
	return err
}

const softDeleteOrder = `-- name: SoftDeleteOrder :exec
UPDATE orders
SET deleted_at = NOW(), status = 'cancelled', updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrder(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteOrder, id)
	return err
}

const sumQtyServedAndQuantity = `-- name: SumQtyServedAndQuantity :one
SELECT
    COALESCE(SUM(qty_served), 0) AS total_served,
    COALESCE(SUM(quantity), 0)   AS total_quantity
FROM order_items
WHERE order_id = ?
`

type SumQtyServedAndQuantityRow struct {
	TotalServed   interface{} `json:"total_served"`
	TotalQuantity interface{} `json:"total_quantity"`
}

func (q *Queries) SumQtyServedAndQuantity(ctx context.Context, orderID string) (SumQtyServedAndQuantityRow, error) {
	row := q.db.QueryRowContext(ctx, sumQtyServedAndQuantity, orderID)
	var i SumQtyServedAndQuantityRow
	err := row.Scan(&i.TotalServed, &i.TotalQuantity)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = ?, updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) UpdateOrderStatus(ctx context.Context, status OrdersStatus, iD string) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, status, iD)
	return err
}

const updateQtyServed = `-- name: UpdateQtyServed :exec
UPDATE order_items
SET qty_served = ?, updated_at = NOW()
WHERE id = ?
`

func (q *Queries) UpdateQtyServed(ctx context.Context, qtyServed int32, iD string) error {
	_, err := q.db.ExecContext(ctx, updateQtyServed, qtyServed, iD)
	return err
}

const upsertOrderSequence = `-- name: UpsertOrderSequence :exec
INSERT INTO order_sequences (date_key, last_seq)
VALUES (?, 1)
ON DUPLICATE KEY UPDATE last_seq = last_seq + 1
`

func (q *Queries) UpsertOrderSequence(ctx context.Context, dateKey time.Time) error {
	_, err := q.db.ExecContext(ctx, upsertOrderSequence, dateKey)
	return err
}
