// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (id, order_id, method, status, amount, expires_at)
VALUES (?, ?, ?, 'pending', ?, ?)
`

type CreatePaymentParams struct {
	ID        string         `json:"id"`
	OrderID   string         `json:"order_id"`
	Method    PaymentsMethod `json:"method"`
	Amount    string         `json:"amount"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.OrderID,
		arg.Method,
		arg.Amount,
		arg.ExpiresAt,
	)
	return err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, method, status, amount, attempt_count, gateway_ref, gateway_data, refunded_amount, expires_at, paid_at, created_at, updated_at, deleted_at FROM payments
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	// database/sql cannot scan NULL into *json.RawMessage; use []byte intermediary.
	var gatewayData []byte
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.AttemptCount,
		&i.GatewayRef,
		&gatewayData,
		&i.RefundedAmount,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	i.GatewayData = json.RawMessage(gatewayData)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, method, status, amount, attempt_count, gateway_ref, gateway_data, refunded_amount, expires_at, paid_at, created_at, updated_at, deleted_at FROM payments
WHERE order_id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	// database/sql cannot scan NULL into *json.RawMessage; use []byte intermediary.
	var gatewayData []byte
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.AttemptCount,
		&i.GatewayRef,
		&gatewayData,
		&i.RefundedAmount,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	i.GatewayData = json.RawMessage(gatewayData)
	return i, err
}

const incrementPaymentAttempt = `-- name: IncrementPaymentAttempt :exec
UPDATE payments
SET attempt_count = attempt_count + 1, updated_at = NOW()
WHERE id = ?
`

func (q *Queries) IncrementPaymentAttempt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementPaymentAttempt, id)
	return err
}

const setPaymentRefunded = `-- name: SetPaymentRefunded :exec
UPDATE payments
SET status = 'refunded', refunded_amount = ?, updated_at = NOW()
WHERE id = ?
`

func (q *Queries) SetPaymentRefunded(ctx context.Context, refundedAmount sql.NullString, iD string) error {
	_, err := q.db.ExecContext(ctx, setPaymentRefunded, refundedAmount, iD)
	return err
}

const softDeletePayment = `-- name: SoftDeletePayment :exec
UPDATE payments
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = ?
`

func (q *Queries) SoftDeletePayment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeletePayment, id)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = ?, gateway_ref = ?, gateway_data = ?, paid_at = ?, updated_at = NOW()
WHERE id = ?
`

type UpdatePaymentStatusParams struct {
	Status      PaymentsStatus  `json:"status"`
	GatewayRef  sql.NullString  `json:"gateway_ref"`
	GatewayData json.RawMessage `json:"gateway_data"`
	PaidAt      sql.NullTime    `json:"paid_at"`
	ID          string          `json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus,
		arg.Status,
		arg.GatewayRef,
		arg.GatewayData,
		arg.PaidAt,
		arg.ID,
	)
	return err
}
