// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"database/sql"
)

const attachToppingToProduct = `-- name: AttachToppingToProduct :exec
INSERT IGNORE INTO product_toppings (product_id, topping_id)
VALUES (?, ?)
`

func (q *Queries) AttachToppingToProduct(ctx context.Context, productID string, toppingID string) error {
	_, err := q.db.ExecContext(ctx, attachToppingToProduct, productID, toppingID)
	return err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (id, name, description, sort_order, is_active)
VALUES (?, ?, ?, ?, 1)
`

func (q *Queries) CreateCategory(ctx context.Context, iD string, name string, description sql.NullString, sortOrder int32) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		iD,
		name,
		description,
		sortOrder,
	)
	return err
}

const createCombo = `-- name: CreateCombo :exec
INSERT INTO combos (id, category_id, name, description, price, image_path, is_available, sort_order)
VALUES (?, ?, ?, ?, ?, ?, 1, ?)
`

type CreateComboParams struct {
	ID          string         `json:"id"`
	CategoryID  sql.NullString `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	ImagePath   sql.NullString `json:"image_path"`
	SortOrder   int32          `json:"sort_order"`
}

func (q *Queries) CreateCombo(ctx context.Context, arg CreateComboParams) error {
	_, err := q.db.ExecContext(ctx, createCombo,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImagePath,
		arg.SortOrder,
	)
	return err
}

const createComboItem = `-- name: CreateComboItem :exec
INSERT INTO combo_items (id, combo_id, product_id, quantity)
VALUES (?, ?, ?, ?)
`

func (q *Queries) CreateComboItem(ctx context.Context, iD string, comboID string, productID string, quantity int32) error {
	_, err := q.db.ExecContext(ctx, createComboItem,
		iD,
		comboID,
		productID,
		quantity,
	)
	return err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (id, category_id, name, description, price, image_path, is_available, sort_order)
VALUES (?, ?, ?, ?, ?, ?, 1, ?)
`

type CreateProductParams struct {
	ID          string         `json:"id"`
	CategoryID  string         `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	ImagePath   sql.NullString `json:"image_path"`
	SortOrder   int32          `json:"sort_order"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImagePath,
		arg.SortOrder,
	)
	return err
}

const createTopping = `-- name: CreateTopping :exec
INSERT INTO toppings (id, name, price, is_available)
VALUES (?, ?, ?, 1)
`

func (q *Queries) CreateTopping(ctx context.Context, iD string, name string, price string) error {
	_, err := q.db.ExecContext(ctx, createTopping, iD, name, price)
	return err
}

const deleteComboItemsByComboID = `-- name: DeleteComboItemsByComboID :exec
DELETE FROM combo_items WHERE combo_id = ?
`

func (q *Queries) DeleteComboItemsByComboID(ctx context.Context, comboID string) error {
	_, err := q.db.ExecContext(ctx, deleteComboItemsByComboID, comboID)
	return err
}

const detachToppingFromProduct = `-- name: DetachToppingFromProduct :exec
DELETE FROM product_toppings
WHERE product_id = ? AND topping_id = ?
`

func (q *Queries) DetachToppingFromProduct(ctx context.Context, productID string, toppingID string) error {
	_, err := q.db.ExecContext(ctx, detachToppingFromProduct, productID, toppingID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, description, sort_order, is_active, created_at, updated_at, deleted_at FROM categories
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getComboByID = `-- name: GetComboByID :one
SELECT id, category_id, name, description, price, image_path, is_available, sort_order, created_at, updated_at, deleted_at FROM combos
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetComboByID(ctx context.Context, id string) (Combo, error) {
	row := q.db.QueryRowContext(ctx, getComboByID, id)
	var i Combo
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImagePath,
		&i.IsAvailable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getComboItems = `-- name: GetComboItems :many
SELECT ci.id, ci.combo_id, ci.product_id, ci.quantity, ci.created_at, ci.updated_at
FROM combo_items ci
WHERE ci.combo_id = ?
ORDER BY ci.created_at ASC
`

func (q *Queries) GetComboItems(ctx context.Context, comboID string) ([]ComboItem, error) {
	rows, err := q.db.QueryContext(ctx, getComboItems, comboID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComboItem{}
	for rows.Next() {
		var i ComboItem
		if err := rows.Scan(
			&i.ID,
			&i.ComboID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, category_id, name, description, price, image_path, is_available, sort_order, created_at, updated_at, deleted_at FROM products
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImagePath,
		&i.IsAvailable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getToppingByID = `-- name: GetToppingByID :one
SELECT id, name, price, is_available, created_at, updated_at, deleted_at FROM toppings
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetToppingByID(ctx context.Context, id string) (Topping, error) {
	row := q.db.QueryRowContext(ctx, getToppingByID, id)
	var i Topping
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getToppingsByProductID = `-- name: GetToppingsByProductID :many
SELECT t.id, t.name, t.price, t.is_available, t.created_at, t.updated_at, t.deleted_at FROM toppings t
INNER JOIN product_toppings pt ON pt.topping_id = t.id
WHERE pt.product_id = ? AND t.deleted_at IS NULL
ORDER BY t.name ASC
`

func (q *Queries) GetToppingsByProductID(ctx context.Context, productID string) ([]Topping, error) {
	rows, err := q.db.QueryContext(ctx, getToppingsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topping{}
	for rows.Next() {
		var i Topping
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description, sort_order, is_active, created_at, updated_at, deleted_at FROM categories
WHERE is_active = 1 AND deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombos = `-- name: ListCombos :many
SELECT id, category_id, name, description, price, image_path, is_available, sort_order, created_at, updated_at, deleted_at FROM combos
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListCombos(ctx context.Context) ([]Combo, error) {
	rows, err := q.db.QueryContext(ctx, listCombos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Combo{}
	for rows.Next() {
		var i Combo
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImagePath,
			&i.IsAvailable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombosAvailable = `-- name: ListCombosAvailable :many
SELECT id, category_id, name, description, price, image_path, is_available, sort_order, created_at, updated_at, deleted_at FROM combos
WHERE is_available = 1 AND deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListCombosAvailable(ctx context.Context) ([]Combo, error) {
	rows, err := q.db.QueryContext(ctx, listCombosAvailable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Combo{}
	for rows.Next() {
		var i Combo
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImagePath,
			&i.IsAvailable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, name, description, price, image_path, is_available, sort_order, created_at, updated_at, deleted_at FROM products
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImagePath,
			&i.IsAvailable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsAvailable = `-- name: ListProductsAvailable :many
SELECT id, category_id, name, description, price, image_path, is_available, sort_order, created_at, updated_at, deleted_at FROM products
WHERE is_available = 1 AND deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListProductsAvailable(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsAvailable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImagePath,
			&i.IsAvailable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategoryAvailable = `-- name: ListProductsByCategoryAvailable :many
SELECT id, category_id, name, description, price, image_path, is_available, sort_order, created_at, updated_at, deleted_at FROM products
WHERE category_id = ? AND is_available = 1 AND deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListProductsByCategoryAvailable(ctx context.Context, categoryID string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategoryAvailable, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImagePath,
			&i.IsAvailable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToppings = `-- name: ListToppings :many
SELECT id, name, price, is_available, created_at, updated_at, deleted_at FROM toppings
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListToppings(ctx context.Context) ([]Topping, error) {
	rows, err := q.db.QueryContext(ctx, listToppings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topping{}
	for rows.Next() {
		var i Topping
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToppingsAvailable = `-- name: ListToppingsAvailable :many
SELECT id, name, price, is_available, created_at, updated_at, deleted_at FROM toppings
WHERE is_available = 1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListToppingsAvailable(ctx context.Context) ([]Topping, error) {
	rows, err := q.db.QueryContext(ctx, listToppingsAvailable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topping{}
	for rows.Next() {
		var i Topping
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteCategory, id)
	return err
}

const softDeleteCombo = `-- name: SoftDeleteCombo :exec
UPDATE combos
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCombo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteCombo, id)
	return err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteProduct, id)
	return err
}

const softDeleteTopping = `-- name: SoftDeleteTopping :exec
UPDATE toppings
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTopping(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteTopping, id)
	return err
}

const toggleProductAvailability = `-- name: ToggleProductAvailability :exec
UPDATE products
SET is_available = ?, updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) ToggleProductAvailability(ctx context.Context, isAvailable bool, iD string) error {
	_, err := q.db.ExecContext(ctx, toggleProductAvailability, isAvailable, iD)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
SET name = ?, description = ?, sort_order = ?, updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) UpdateCategory(ctx context.Context, name string, description sql.NullString, sortOrder int32, iD string) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		name,
		description,
		sortOrder,
		iD,
	)
	return err
}

const updateCombo = `-- name: UpdateCombo :exec
UPDATE combos
SET category_id = ?, name = ?, description = ?, price = ?, image_path = ?, sort_order = ?, updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateComboParams struct {
	CategoryID  sql.NullString `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	ImagePath   sql.NullString `json:"image_path"`
	SortOrder   int32          `json:"sort_order"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateCombo(ctx context.Context, arg UpdateComboParams) error {
	_, err := q.db.ExecContext(ctx, updateCombo,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImagePath,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET category_id = ?, name = ?, description = ?, price = ?, image_path = ?, sort_order = ?, updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateProductParams struct {
	CategoryID  string         `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	ImagePath   sql.NullString `json:"image_path"`
	SortOrder   int32          `json:"sort_order"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImagePath,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updateTopping = `-- name: UpdateTopping :exec
UPDATE toppings
SET name = ?, price = ?, updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) UpdateTopping(ctx context.Context, name string, price string, iD string) error {
	_, err := q.db.ExecContext(ctx, updateTopping, name, price, iD)
	return err
}
