// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AttachToppingToProduct(ctx context.Context, productID string, toppingID string) error
	CountActiveSessionsByStaff(ctx context.Context, staffID string) (int64, error)
	CreateCategory(ctx context.Context, iD string, name string, description sql.NullString, sortOrder int32) error
	CreateCombo(ctx context.Context, arg CreateComboParams) error
	CreateComboItem(ctx context.Context, iD string, comboID string, productID string, quantity int32) error
	CreateFileAttachment(ctx context.Context, arg CreateFileAttachmentParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateTopping(ctx context.Context, iD string, name string, price string) error
	DeleteComboItemsByComboID(ctx context.Context, comboID string) error
	DeleteOldestSessionByStaff(ctx context.Context, staffID string) error
	DeleteOrphanFilesOlderThan24h(ctx context.Context) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteRefreshTokensByStaff(ctx context.Context, staffID string) error
	DetachToppingFromProduct(ctx context.Context, productID string, toppingID string) error
	GetActiveOrderByTable(ctx context.Context, tableID sql.NullString) (Order, error)
	GetCategoryByID(ctx context.Context, id string) (Category, error)
	GetComboByID(ctx context.Context, id string) (Combo, error)
	GetComboItems(ctx context.Context, comboID string) ([]ComboItem, error)
	GetFileAttachmentByID(ctx context.Context, id string) (FileAttachment, error)
	GetOrderByID(ctx context.Context, id string) (Order, error)
	GetOrderItemByID(ctx context.Context, id string) (OrderItem, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID string) ([]OrderItem, error)
	GetOrderSequence(ctx context.Context, dateKey time.Time) (int32, error)
	GetPaymentByID(ctx context.Context, id string) (Payment, error)
	GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error)
	GetProductByID(ctx context.Context, id string) (Product, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetStaffByID(ctx context.Context, id string) (Staff, error)
	GetStaffByUsername(ctx context.Context, username string) (Staff, error)
	GetToppingByID(ctx context.Context, id string) (Topping, error)
	GetToppingsByProductID(ctx context.Context, productID string) ([]Topping, error)
	IncrementPaymentAttempt(ctx context.Context, id string) error
	LinkFileToEntity(ctx context.Context, entityType sql.NullString, entityID sql.NullString, iD string) error
	ListActiveSessionsByStaff(ctx context.Context, staffID string) ([]RefreshToken, error)
	ListAllOrders(ctx context.Context, limit int32, offset int32) ([]Order, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCombos(ctx context.Context) ([]Combo, error)
	ListCombosAvailable(ctx context.Context) ([]Combo, error)
	ListOrdersByStatus(ctx context.Context, status OrdersStatus, limit int32, offset int32) ([]Order, error)
	ListOrphanFilesOlderThan24h(ctx context.Context) ([]FileAttachment, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsAvailable(ctx context.Context) ([]Product, error)
	ListProductsByCategoryAvailable(ctx context.Context, categoryID string) ([]Product, error)
	ListToppings(ctx context.Context) ([]Topping, error)
	ListToppingsAvailable(ctx context.Context) ([]Topping, error)
	// recalculateTotalAmount MUST be called after every order_items mutation.
	// Skipping this causes total_amount drift and wrong payment charges.
	RecalculateTotalAmount(ctx context.Context, id string) error
	SetPaymentRefunded(ctx context.Context, refundedAmount sql.NullString, iD string) error
	SetStaffActive(ctx context.Context, isActive bool, iD string) error
	SoftDeleteCategory(ctx context.Context, id string) error
	SoftDeleteCombo(ctx context.Context, id string) error
	SoftDeleteOrder(ctx context.Context, id string) error
	SoftDeletePayment(ctx context.Context, id string) error
	SoftDeleteProduct(ctx context.Context, id string) error
	SoftDeleteTopping(ctx context.Context, id string) error
	SumQtyServedAndQuantity(ctx context.Context, orderID string) (SumQtyServedAndQuantityRow, error)
	ToggleProductAvailability(ctx context.Context, isAvailable bool, iD string) error
	UpdateCategory(ctx context.Context, name string, description sql.NullString, sortOrder int32, iD string) error
	UpdateCombo(ctx context.Context, arg UpdateComboParams) error
	UpdateOrderStatus(ctx context.Context, status OrdersStatus, iD string) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateQtyServed(ctx context.Context, qtyServed int32, iD string) error
	UpdateRefreshTokenLastUsed(ctx context.Context, tokenHash string) error
	UpdateTopping(ctx context.Context, name string, price string, iD string) error
	UpsertOrderSequence(ctx context.Context, dateKey time.Time) error
}

var _ Querier = (*Queries)(nil)
