// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createStaffTask = `-- name: CreateStaffTask :exec
INSERT INTO staff_tasks (id, title, description, assigned_to, assigned_by, priority, status, due_at, due_time_start, due_time_end, notes)
VALUES (?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?, ?)
`

type CreateStaffTaskParams struct {
	ID           string             `json:"id"`
	Title        string             `json:"title"`
	Description  sql.NullString     `json:"description"`
	AssignedTo   string             `json:"assigned_to"`
	AssignedBy   string             `json:"assigned_by"`
	Priority     StaffTasksPriority `json:"priority"`
	DueAt        time.Time          `json:"due_at"`
	DueTimeStart sql.NullString     `json:"due_time_start"`
	DueTimeEnd   sql.NullString     `json:"due_time_end"`
	Notes        sql.NullString     `json:"notes"`
}

func (q *Queries) CreateStaffTask(ctx context.Context, arg CreateStaffTaskParams) error {
	_, err := q.db.ExecContext(ctx, createStaffTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AssignedTo,
		arg.AssignedBy,
		arg.Priority,
		arg.DueAt,
		arg.DueTimeStart,
		arg.DueTimeEnd,
		arg.Notes,
	)
	return err
}

const getDailyTaskMetrics = `-- name: GetDailyTaskMetrics :one
SELECT
  COUNT(*)                                                            AS total_tasks,
  SUM(CASE WHEN status = 'completed'   THEN 1 ELSE 0 END)            AS completed_tasks,
  SUM(CASE WHEN status = 'in_progress' THEN 1 ELSE 0 END)            AS in_progress_tasks,
  SUM(CASE WHEN status = 'overdue'     THEN 1 ELSE 0 END)            AS overdue_tasks
FROM staff_tasks
WHERE DATE(due_at) = ?
  AND deleted_at IS NULL
`

type GetDailyTaskMetricsRow struct {
	TotalTasks      int64       `json:"total_tasks"`
	CompletedTasks  interface{} `json:"completed_tasks"`
	InProgressTasks interface{} `json:"in_progress_tasks"`
	OverdueTasks    interface{} `json:"overdue_tasks"`
}

func (q *Queries) GetDailyTaskMetrics(ctx context.Context, dueAt time.Time) (GetDailyTaskMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, getDailyTaskMetrics, dueAt)
	var i GetDailyTaskMetricsRow
	err := row.Scan(
		&i.TotalTasks,
		&i.CompletedTasks,
		&i.InProgressTasks,
		&i.OverdueTasks,
	)
	return i, err
}

const getStaffTaskByID = `-- name: GetStaffTaskByID :one
SELECT id, title, description, assigned_to, assigned_by, due_at, completed_at, created_at, updated_at, deleted_at, priority, notes, due_time_start, due_time_end, status FROM staff_tasks
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetStaffTaskByID(ctx context.Context, id string) (StaffTask, error) {
	row := q.db.QueryRowContext(ctx, getStaffTaskByID, id)
	var i StaffTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Priority,
		&i.Notes,
		&i.DueTimeStart,
		&i.DueTimeEnd,
		&i.Status,
	)
	return i, err
}

const getStaffTaskStats = `-- name: GetStaffTaskStats :many
SELECT
  s.id                                                                    AS staff_id,
  s.full_name                                                             AS staff_name,
  s.role,
  COUNT(t.id)                                                             AS assigned_count,
  CAST(SUM(CASE WHEN t.status = 'completed' THEN 1 ELSE 0 END) AS SIGNED) AS completed_count,
  CASE
    WHEN COUNT(t.id) = 0 THEN 0
    ELSE CAST(ROUND(100.0 * SUM(CASE WHEN t.status = 'completed' THEN 1 ELSE 0 END) / COUNT(t.id)) AS SIGNED)
  END                                                                     AS completion_rate,
  CAST(MAX(CASE WHEN t.status = 'overdue' THEN 1 ELSE 0 END) AS SIGNED)  AS has_overdue
FROM staff s
LEFT JOIN staff_tasks t
  ON t.assigned_to = s.id
  AND DATE(t.due_at) = ?
  AND t.deleted_at IS NULL
WHERE s.deleted_at IS NULL
  AND s.is_active = 1
GROUP BY s.id, s.full_name, s.role
ORDER BY s.full_name ASC
`

type GetStaffTaskStatsRow struct {
	StaffID        string    `json:"staff_id"`
	StaffName      string    `json:"staff_name"`
	Role           StaffRole `json:"role"`
	AssignedCount  int64     `json:"assigned_count"`
	CompletedCount int64     `json:"completed_count"`
	CompletionRate int64     `json:"completion_rate"`
	HasOverdue     int64     `json:"has_overdue"`
}

func (q *Queries) GetStaffTaskStats(ctx context.Context, dueAt time.Time) ([]GetStaffTaskStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStaffTaskStats, dueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaffTaskStatsRow{}
	for rows.Next() {
		var i GetStaffTaskStatsRow
		if err := rows.Scan(
			&i.StaffID,
			&i.StaffName,
			&i.Role,
			&i.AssignedCount,
			&i.CompletedCount,
			&i.CompletionRate,
			&i.HasOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffTasksByDate = `-- name: GetStaffTasksByDate :many
SELECT id, title, description, assigned_to, assigned_by, due_at, completed_at, created_at, updated_at, deleted_at, priority, notes, due_time_start, due_time_end, status FROM staff_tasks
WHERE assigned_to = ?
  AND DATE(due_at) = ?
  AND deleted_at IS NULL
ORDER BY
  CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
  due_at ASC
`

func (q *Queries) GetStaffTasksByDate(ctx context.Context, assignedTo string, dueAt time.Time) ([]StaffTask, error) {
	rows, err := q.db.QueryContext(ctx, getStaffTasksByDate, assignedTo, dueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffTask{}
	for rows.Next() {
		var i StaffTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AssignedTo,
			&i.AssignedBy,
			&i.DueAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Priority,
			&i.Notes,
			&i.DueTimeStart,
			&i.DueTimeEnd,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
