// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countGuideProgress = `-- name: CountGuideProgress :one
SELECT COUNT(*) FROM training_progress
WHERE guide_id = ?
`

func (q *Queries) CountGuideProgress(ctx context.Context, guideID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuideProgress, guideID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuizAttempts = `-- name: CountQuizAttempts :one
SELECT COUNT(*) FROM quiz_attempts
WHERE progress_id = ?
`

func (q *Queries) CountQuizAttempts(ctx context.Context, progressID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuizAttempts, progressID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrainingGuide = `-- name: CreateTrainingGuide :exec
INSERT INTO training_guides (
    id, title, role, description, cover_image_url, youtube_url,
    quality_kpi_target, quantity_kpi_target, pass_threshold, max_attempts,
    published, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTrainingGuideParams struct {
	ID                string             `json:"id"`
	Title             string             `json:"title"`
	Role              TrainingGuidesRole `json:"role"`
	Description       sql.NullString     `json:"description"`
	CoverImageUrl     sql.NullString     `json:"cover_image_url"`
	YoutubeUrl        sql.NullString     `json:"youtube_url"`
	QualityKpiTarget  sql.NullString     `json:"quality_kpi_target"`
	QuantityKpiTarget sql.NullString     `json:"quantity_kpi_target"`
	PassThreshold     int32              `json:"pass_threshold"`
	MaxAttempts       int32              `json:"max_attempts"`
	Published         bool               `json:"published"`
	CreatedBy         sql.NullString     `json:"created_by"`
}

func (q *Queries) CreateTrainingGuide(ctx context.Context, arg CreateTrainingGuideParams) error {
	_, err := q.db.ExecContext(ctx, createTrainingGuide,
		arg.ID,
		arg.Title,
		arg.Role,
		arg.Description,
		arg.CoverImageUrl,
		arg.YoutubeUrl,
		arg.QualityKpiTarget,
		arg.QuantityKpiTarget,
		arg.PassThreshold,
		arg.MaxAttempts,
		arg.Published,
		arg.CreatedBy,
	)
	return err
}

const deleteGuideRoles = `-- name: DeleteGuideRoles :exec
DELETE FROM training_guide_roles
WHERE guide_id = ?
`

func (q *Queries) DeleteGuideRoles(ctx context.Context, guideID string) error {
	_, err := q.db.ExecContext(ctx, deleteGuideRoles, guideID)
	return err
}

const getGuideRoles = `-- name: GetGuideRoles :many
SELECT role FROM training_guide_roles
WHERE guide_id = ?
`

func (q *Queries) GetGuideRoles(ctx context.Context, guideID string) ([]TrainingGuideRolesRole, error) {
	rows, err := q.db.QueryContext(ctx, getGuideRoles, guideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingGuideRolesRole{}
	for rows.Next() {
		var role TrainingGuideRolesRole
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffProgress = `-- name: GetStaffProgress :one
SELECT id, guide_id, staff_id, watched_percent, manager_notes, created_at, updated_at FROM training_progress
WHERE guide_id = ? AND staff_id = ?
LIMIT 1
`

func (q *Queries) GetStaffProgress(ctx context.Context, guideID string, staffID string) (TrainingProgress, error) {
	row := q.db.QueryRowContext(ctx, getStaffProgress, guideID, staffID)
	var i TrainingProgress
	err := row.Scan(
		&i.ID,
		&i.GuideID,
		&i.StaffID,
		&i.WatchedPercent,
		&i.ManagerNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainingGuide = `-- name: GetTrainingGuide :one
SELECT id, title, role, description, cover_image_url, youtube_url, quality_kpi_target, quantity_kpi_target, pass_threshold, max_attempts, published, created_by, created_at, updated_at, deleted_at FROM training_guides
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetTrainingGuide(ctx context.Context, id string) (TrainingGuide, error) {
	row := q.db.QueryRowContext(ctx, getTrainingGuide, id)
	var i TrainingGuide
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Role,
		&i.Description,
		&i.CoverImageUrl,
		&i.YoutubeUrl,
		&i.QualityKpiTarget,
		&i.QuantityKpiTarget,
		&i.PassThreshold,
		&i.MaxAttempts,
		&i.Published,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertGuideRole = `-- name: InsertGuideRole :exec
INSERT IGNORE INTO training_guide_roles (guide_id, role)
VALUES (?, ?)
`

func (q *Queries) InsertGuideRole(ctx context.Context, guideID string, role TrainingGuideRolesRole) error {
	_, err := q.db.ExecContext(ctx, insertGuideRole, guideID, role)
	return err
}

const insertQuizAttempt = `-- name: InsertQuizAttempt :exec
INSERT INTO quiz_attempts (id, progress_id, score, passed, attempted_at)
VALUES (?, ?, ?, ?, NOW())
`

func (q *Queries) InsertQuizAttempt(ctx context.Context, iD string, progressID string, score int32, passed bool) error {
	_, err := q.db.ExecContext(ctx, insertQuizAttempt,
		iD,
		progressID,
		score,
		passed,
	)
	return err
}

const listGuideProgress = `-- name: ListGuideProgress :many
SELECT
    tp.id,
    tp.guide_id,
    tp.staff_id,
    tp.watched_percent,
    tp.manager_notes,
    tp.created_at,
    tp.updated_at,
    s.full_name AS staff_name,
    s.role      AS staff_role
FROM training_progress tp
JOIN staff s ON s.id = tp.staff_id
WHERE tp.guide_id = ?
ORDER BY s.full_name ASC
LIMIT ? OFFSET ?
`

type ListGuideProgressRow struct {
	ID             string         `json:"id"`
	GuideID        string         `json:"guide_id"`
	StaffID        string         `json:"staff_id"`
	WatchedPercent int32          `json:"watched_percent"`
	ManagerNotes   sql.NullString `json:"manager_notes"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	StaffName      string         `json:"staff_name"`
	StaffRole      StaffRole      `json:"staff_role"`
}

func (q *Queries) ListGuideProgress(ctx context.Context, guideID string, limit int32, offset int32) ([]ListGuideProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuideProgress, guideID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuideProgressRow{}
	for rows.Next() {
		var i ListGuideProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.GuideID,
			&i.StaffID,
			&i.WatchedPercent,
			&i.ManagerNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StaffName,
			&i.StaffRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAttempts = `-- name: ListQuizAttempts :many
SELECT id, progress_id, score, passed, attempted_at, created_at FROM quiz_attempts
WHERE progress_id = ?
ORDER BY attempted_at ASC
`

func (q *Queries) ListQuizAttempts(ctx context.Context, progressID string) ([]QuizAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listQuizAttempts, progressID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.ProgressID,
			&i.Score,
			&i.Passed,
			&i.AttemptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingGuides = `-- name: ListTrainingGuides :many
SELECT id, title, role, description, cover_image_url, youtube_url, quality_kpi_target, quantity_kpi_target, pass_threshold, max_attempts, published, created_by, created_at, updated_at, deleted_at FROM training_guides
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTrainingGuides(ctx context.Context) ([]TrainingGuide, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingGuides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingGuide{}
	for rows.Next() {
		var i TrainingGuide
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Role,
			&i.Description,
			&i.CoverImageUrl,
			&i.YoutubeUrl,
			&i.QualityKpiTarget,
			&i.QuantityKpiTarget,
			&i.PassThreshold,
			&i.MaxAttempts,
			&i.Published,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingGuidesByRole = `-- name: ListTrainingGuidesByRole :many
SELECT id, title, role, description, cover_image_url, youtube_url, quality_kpi_target, quantity_kpi_target, pass_threshold, max_attempts, published, created_by, created_at, updated_at, deleted_at FROM training_guides
WHERE role = ? AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTrainingGuidesByRole(ctx context.Context, role TrainingGuidesRole) ([]TrainingGuide, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingGuidesByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingGuide{}
	for rows.Next() {
		var i TrainingGuide
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Role,
			&i.Description,
			&i.CoverImageUrl,
			&i.YoutubeUrl,
			&i.QualityKpiTarget,
			&i.QuantityKpiTarget,
			&i.PassThreshold,
			&i.MaxAttempts,
			&i.Published,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTrainingGuide = `-- name: SoftDeleteTrainingGuide :exec
UPDATE training_guides
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTrainingGuide(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteTrainingGuide, id)
	return err
}

const updateManagerNotes = `-- name: UpdateManagerNotes :exec
UPDATE training_progress
SET manager_notes = ?, updated_at = NOW()
WHERE guide_id = ? AND staff_id = ?
`

func (q *Queries) UpdateManagerNotes(ctx context.Context, managerNotes sql.NullString, guideID string, staffID string) error {
	_, err := q.db.ExecContext(ctx, updateManagerNotes, managerNotes, guideID, staffID)
	return err
}

const updateTrainingGuide = `-- name: UpdateTrainingGuide :exec
UPDATE training_guides
SET title = ?, role = ?, description = ?, cover_image_url = ?, youtube_url = ?,
    quality_kpi_target = ?, quantity_kpi_target = ?, pass_threshold = ?,
    max_attempts = ?, published = ?, updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateTrainingGuideParams struct {
	Title             string             `json:"title"`
	Role              TrainingGuidesRole `json:"role"`
	Description       sql.NullString     `json:"description"`
	CoverImageUrl     sql.NullString     `json:"cover_image_url"`
	YoutubeUrl        sql.NullString     `json:"youtube_url"`
	QualityKpiTarget  sql.NullString     `json:"quality_kpi_target"`
	QuantityKpiTarget sql.NullString     `json:"quantity_kpi_target"`
	PassThreshold     int32              `json:"pass_threshold"`
	MaxAttempts       int32              `json:"max_attempts"`
	Published         bool               `json:"published"`
	ID                string             `json:"id"`
}

func (q *Queries) UpdateTrainingGuide(ctx context.Context, arg UpdateTrainingGuideParams) error {
	_, err := q.db.ExecContext(ctx, updateTrainingGuide,
		arg.Title,
		arg.Role,
		arg.Description,
		arg.CoverImageUrl,
		arg.YoutubeUrl,
		arg.QualityKpiTarget,
		arg.QuantityKpiTarget,
		arg.PassThreshold,
		arg.MaxAttempts,
		arg.Published,
		arg.ID,
	)
	return err
}

const upsertStaffProgress = `-- name: UpsertStaffProgress :exec
INSERT INTO training_progress (id, guide_id, staff_id, watched_percent)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    watched_percent = VALUES(watched_percent),
    updated_at = NOW()
`

func (q *Queries) UpsertStaffProgress(ctx context.Context, iD string, guideID string, staffID string, watchedPercent int32) error {
	_, err := q.db.ExecContext(ctx, upsertStaffProgress,
		iD,
		guideID,
		staffID,
		watchedPercent,
	)
	return err
}
